C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msealgorithm.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe mseany.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe mseasyncshared.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msecregistered.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msefunctional.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe mseivector.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe mselegacyhelpers.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msemsearray.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msemsestring.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msemsevector.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msemstdarray.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msemstdstring.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msemstdvector.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msenorad.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msenoradproxy.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe mseoptional.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msepointerbasics.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msepoly.h
rem C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe mseprimitives.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe mserefcounting.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe mseregistered.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe mseregisteredproxy.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msescope.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msescopeatomic.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msestaticimmutable.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msethreadlocal.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msetl.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msetl_example2.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msetl_example3.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msetl_example_defs.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msetuple.h
C:\usr\dev\tmp\match_replace1\Debug\match_replace1.exe msevector_test.h
